import type { Metadata } from "next";
import "./globals.css";
import { toast, ToastContainer } from "react-toastify";



export const metadata: Metadata = {
  title: "Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer position="top-right"/>
      </body>
    </html>
  );
}
